import './stencil.core';
/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */
declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }

  interface HTMLAttributes {}
}


import {
  MyHeader as MyHeader
} from './components/my-header/my-header';

declare global {
  interface HTMLMyHeaderElement extends MyHeader, HTMLStencilElement {
  }
  var HTMLMyHeaderElement: {
    prototype: HTMLMyHeaderElement;
    new (): HTMLMyHeaderElement;
  };
  interface HTMLElementTagNameMap {
    "my-header": HTMLMyHeaderElement;
  }
  interface ElementTagNameMap {
    "my-header": HTMLMyHeaderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-header": JSXElements.MyHeaderAttributes;
    }
  }
  namespace JSXElements {
    export interface MyHeaderAttributes extends HTMLAttributes {
      first?: string;
      second?: string;
      third?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
